export const mockMoviesData = [
	{
		title: 'The Shawshank Redemption',
		year: '1994',
		genre: ['Drama'],
		country: ['USA'],
		imdb_rating: 9.3,
		oscar_nominations: 7,
		oscar_winning: 0,
		cast: ['Tim Robbins', 'Morgan Freeman'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Film Editing',
			'Best Original Score',
			'Best Sound Mixing',
		],
		oscar_winning_list: [],
	},
	{
		title: 'The Godfather',
		year: '1972',
		genre: ['Crime', 'Drama'],
		country: ['USA'],
		imdb_rating: 9.2,
		oscar_nominations: 11,
		oscar_winning: 3,
		cast: ['Marlon Brando', 'Al Pacino'],
		language: ['English', 'Italian'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Supporting Actor',
			'Best Director',
			'Best Adapted Screenplay',
			'Best Costume Design',
			'Best Film Editing',
			'Best Original Score',
			'Best Sound Mixing',
			'Best Art Direction',
			'Best Cinematography',
		],
		oscar_winning_list: ['Best Picture', 'Best Actor', 'Best Adapted Screenplay'],
	},
	{
		title: 'The Dark Knight',
		year: '2008',
		genre: ['Action', 'Crime', 'Drama'],
		country: ['USA', 'UK'],
		imdb_rating: 9.0,
		oscar_nominations: 8,
		oscar_winning: 2,
		cast: ['Christian Bale', 'Heath Ledger'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Supporting Actor',
			'Best Cinematography',
			'Best Film Editing',
			'Best Art Direction',
			'Best Makeup',
			'Best Sound Editing',
			'Best Sound Mixing',
			'Best Visual Effects',
		],
		oscar_winning_list: ['Best Supporting Actor', 'Best Sound Editing'],
	},
	{
		title: 'Pulp Fiction',
		year: '1994',
		genre: ['Crime', 'Drama'],
		country: ['USA'],
		imdb_rating: 8.9,
		oscar_nominations: 7,
		oscar_winning: 1,
		cast: ['John Travolta', 'Uma Thurman'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Actor',
			'Best Supporting Actor',
			'Best Supporting Actress',
			'Best Original Screenplay',
			'Best Film Editing',
		],
		oscar_winning_list: ['Best Original Screenplay'],
	},
	{
		title: "Schindler's List",
		year: '1993',
		genre: ['Biography', 'Drama', 'History'],
		country: ['USA'],
		imdb_rating: 8.9,
		oscar_nominations: 12,
		oscar_winning: 7,
		cast: ['Liam Neeson', 'Ben Kingsley'],
		language: ['English', 'Hebrew', 'German', 'Polish'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Actor',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Art Direction',
			'Best Costume Design',
			'Best Film Editing',
			'Best Makeup',
			'Best Original Score',
			'Best Sound',
			'Best Sound Editing',
		],
		oscar_winning_list: [
			'Best Picture',
			'Best Director',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Art Direction',
			'Best Film Editing',
			'Best Original Score',
		],
	},

	{
		title: 'Fight Club',
		year: '1999',
		genre: ['Drama'],
		country: ['USA'],
		imdb_rating: 8.8,
		oscar_nominations: 1,
		oscar_winning: 0,
		cast: ['Brad Pitt', 'Edward Norton'],
		language: ['English'],
		oscar_nominations_list: ['Best Sound Effects Editing'],
		oscar_winning_list: [],
	},
	{
		title: 'Forrest Gump',
		year: '1994',
		genre: ['Drama', 'Romance'],
		country: ['USA'],
		imdb_rating: 8.8,
		oscar_nominations: 13,
		oscar_winning: 6,
		cast: ['Tom Hanks', 'Robin Wright'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Actor',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Art Direction',
			'Best Costume Design',
			'Best Film Editing',
			'Best Makeup',
			'Best Original Score',
			'Best Sound Mixing',
			'Best Sound Editing',
			'Best Visual Effects',
		],
		oscar_winning_list: [
			'Best Picture',
			'Best Director',
			'Best Actor',
			'Best Adapted Screenplay',
			'Best Film Editing',
			'Best Visual Effects',
		],
	},

	{
		title: 'Inception',
		year: '2010',
		genre: ['Action', 'Adventure', 'Sci-Fi'],
		country: ['USA', 'UK'],
		imdb_rating: 8.8,
		oscar_nominations: 8,
		oscar_winning: 4,
		cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt'],
		language: ['English', 'Japanese', 'French'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Original Screenplay',
			'Best Cinematography',
			'Best Art Direction',
			'Best Original Score',
			'Best Visual Effects',
			'Best Sound Mixing',
			'Best Sound Editing',
		],
		oscar_winning_list: [
			'Best Cinematography',
			'Best Visual Effects',
			'Best Sound Mixing',
			'Best Sound Editing',
		],
	},
	{
		title: 'The Matrix',
		year: '1999',
		genre: ['Action', 'Sci-Fi'],
		country: ['USA', 'Australia'],
		imdb_rating: 8.7,
		oscar_nominations: 4,
		oscar_winning: 4,
		cast: ['Keanu Reeves', 'Laurence Fishburne'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Film Editing',
			'Best Sound',
			'Best Visual Effects',
			'Best Sound Editing',
		],
		oscar_winning_list: [
			'Best Film Editing',
			'Best Sound',
			'Best Visual Effects',
			'Best Sound Editing',
		],
	},
	{
		title: 'The Empire Strikes Back',
		year: '1980',
		genre: ['Action', 'Adventure', 'Fantasy'],
		country: ['USA'],
		imdb_rating: 8.7,
		oscar_nominations: 3,
		oscar_winning: 2,
		cast: ['Mark Hamill', 'Harrison Ford'],
		language: ['English'],
		oscar_nominations_list: ['Best Art Direction', 'Best Original Score', 'Best Sound Mixing'],
		oscar_winning_list: ['Best Art Direction', 'Best Original Score'],
	},
	{
		title: 'Parasite',
		year: '2019',
		genre: ['Drama', 'Thriller'],
		country: ['South Korea'],
		imdb_rating: 8.6,
		oscar_nominations: 6,
		oscar_winning: 4,
		cast: ['Song Kang-ho', 'Cho Yeo-jeong'],
		language: ['Korean'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Original Screenplay',
			'Best International Feature Film',
			'Best Film Editing',
			'Best Production Design',
		],
		oscar_winning_list: [
			'Best Picture',
			'Best Director',
			'Best Original Screenplay',
			'Best International Feature Film',
		],
	},
	{
		title: 'Gladiator',
		year: '2000',
		genre: ['Action', 'Drama', 'Adventure'],
		country: ['USA', 'UK'],
		imdb_rating: 8.5,
		oscar_nominations: 12,
		oscar_winning: 5,
		cast: ['Russell Crowe', 'Joaquin Phoenix'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Supporting Actor',
			'Best Director',
			'Best Original Screenplay',
			'Best Cinematography',
			'Best Costume Design',
			'Best Film Editing',
			'Best Art Direction',
			'Best Original Score',
			'Best Visual Effects',
			'Best Sound Mixing',
		],
		oscar_winning_list: [
			'Best Picture',
			'Best Actor',
			'Best Costume Design',
			'Best Visual Effects',
			'Best Sound Mixing',
		],
	},
	{
		title: 'La La Land',
		year: '2016',
		genre: ['Drama', 'Romance', 'Musical'],
		country: ['USA'],
		imdb_rating: 8.0,
		oscar_nominations: 14,
		oscar_winning: 6,
		cast: ['Ryan Gosling', 'Emma Stone'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Actress',
			'Best Director',
			'Best Original Screenplay',
			'Best Cinematography',
			'Best Costume Design',
			'Best Film Editing',
			'Best Art Direction',
			'Best Original Score',
			'Best Original Song',
			'Best Sound Mixing',
			'Best Sound Editing',
			'Best Production Design',
		],
		oscar_winning_list: [
			'Best Actress',
			'Best Director',
			'Best Original Score',
			'Best Cinematography',
			'Best Production Design',
			'Best Original Song',
		],
	},
	{
		title: 'Mad Max: Fury Road',
		year: '2015',
		genre: ['Action', 'Adventure', 'Sci-Fi'],
		country: ['Australia', 'USA'],
		imdb_rating: 8.1,
		oscar_nominations: 10,
		oscar_winning: 6,
		cast: ['Tom Hardy', 'Charlize Theron'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Cinematography',
			'Best Costume Design',
			'Best Film Editing',
			'Best Art Direction',
			'Best Visual Effects',
			'Best Sound Mixing',
			'Best Sound Editing',
			'Best Makeup',
		],
		oscar_winning_list: [
			'Best Costume Design',
			'Best Film Editing',
			'Best Art Direction',
			'Best Makeup',
			'Best Sound Mixing',
			'Best Sound Editing',
		],
	},
	{
		title: 'Interstellar',
		year: '2014',
		genre: ['Adventure', 'Drama', 'Sci-Fi'],
		country: ['USA', 'UK'],
		imdb_rating: 8.6,
		oscar_nominations: 5,
		oscar_winning: 1,
		cast: ['Matthew McConaughey', 'Anne Hathaway'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Visual Effects',
			'Best Original Score',
			'Best Production Design',
			'Best Sound Mixing',
			'Best Sound Editing',
		],
		oscar_winning_list: ['Best Visual Effects'],
	},
	{
		title: 'The Grand Budapest Hotel',
		year: '2014',
		genre: ['Adventure', 'Comedy', 'Drama'],
		country: ['USA', 'Germany'],
		imdb_rating: 8.1,
		oscar_nominations: 9,
		oscar_winning: 4,
		cast: ['Ralph Fiennes', 'Tony Revolori'],
		language: ['English', 'French', 'German'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Original Screenplay',
			'Best Cinematography',
			'Best Costume Design',
			'Best Film Editing',
			'Best Makeup',
			'Best Original Score',
			'Best Production Design',
		],
		oscar_winning_list: [
			'Best Costume Design',
			'Best Original Score',
			'Best Production Design',
			'Best Makeup',
		],
	},
	{
		title: 'Whiplash',
		year: '2014',
		genre: ['Drama', 'Music'],
		country: ['USA'],
		imdb_rating: 8.5,
		oscar_nominations: 5,
		oscar_winning: 3,
		cast: ['Miles Teller', 'J.K. Simmons'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Supporting Actor',
			'Best Film Editing',
			'Best Sound Mixing',
			'Best Adapted Screenplay',
		],
		oscar_winning_list: ['Best Supporting Actor', 'Best Film Editing', 'Best Sound Mixing'],
	},
	{
		title: 'Django Unchained',
		year: '2012',
		genre: ['Drama', 'Western'],
		country: ['USA'],
		imdb_rating: 8.4,
		oscar_nominations: 5,
		oscar_winning: 2,
		cast: ['Jamie Foxx', 'Christoph Waltz'],
		language: ['English', 'German', 'French'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Supporting Actor',
			'Best Original Screenplay',
			'Best Cinematography',
			'Best Sound Editing',
		],
		oscar_winning_list: ['Best Supporting Actor', 'Best Original Screenplay'],
	},
	{
		title: 'The Social Network',
		year: '2010',
		genre: ['Biography', 'Drama'],
		country: ['USA'],
		imdb_rating: 7.8,
		oscar_nominations: 8,
		oscar_winning: 3,
		cast: ['Jesse Eisenberg', 'Andrew Garfield'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Director',
			'Best Adapted Screenplay',
			'Best Film Editing',
			'Best Cinematography',
			'Best Original Score',
			'Best Sound Mixing',
		],
		oscar_winning_list: ['Best Adapted Screenplay', 'Best Film Editing', 'Best Original Score'],
	},
	{
		title: 'Slumdog Millionaire',
		year: '2008',
		genre: ['Drama', 'Romance'],
		country: ['UK', 'India'],
		imdb_rating: 8.0,
		oscar_nominations: 10,
		oscar_winning: 8,
		cast: ['Dev Patel', 'Freida Pinto'],
		language: ['English', 'Hindi'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Film Editing',
			'Best Original Score',
			'Best Original Song',
			'Best Sound Mixing',
			'Best Sound Editing',
			'Best Art Direction',
		],
		oscar_winning_list: [
			'Best Picture',
			'Best Director',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Film Editing',
			'Best Original Score',
			'Best Original Song',
			'Best Sound Mixing',
		],
	},
	{
		title: 'The Wolf of Wall Street',
		year: '2013',
		genre: ['Biography', 'Comedy', 'Crime'],
		country: ['USA'],
		imdb_rating: 8.2,
		oscar_nominations: 5,
		oscar_winning: 0,
		cast: ['Leonardo DiCaprio', 'Jonah Hill'],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Actor',
			'Best Supporting Actor',
			'Best Director',
			'Best Adapted Screenplay',
		],
		oscar_winning_list: [],
	},
	{
		title: '12 Years a Slave',
		year: '2013',
		genre: ['Biography', 'Drama', 'History'],
		country: ['USA', 'UK'],
		imdb_rating: 8.1,
		oscar_nominations: 9,
		oscar_winning: 3,
		cast: ['Chiwetel Ejiofor', "Lupita Nyong'o"],
		language: ['English'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Director',
			'Best Actor',
			'Best Supporting Actress',
			'Best Adapted Screenplay',
			'Best Cinematography',
			'Best Costume Design',
			'Best Film Editing',
			'Best Production Design',
		],
		oscar_winning_list: ['Best Picture', 'Best Supporting Actress', 'Best Adapted Screenplay'],
	},
	{
		title: 'Black Panther',
		year: '2018',
		genre: ['Action', 'Adventure', 'Sci-Fi'],
		country: ['USA'],
		imdb_rating: 7.3,
		oscar_nominations: 7,
		oscar_winning: 3,
		cast: ['Chadwick Boseman', 'Michael B. Jordan'],
		language: ['English', 'Xhosa'],
		oscar_nominations_list: [
			'Best Picture',
			'Best Costume Design',
			'Best Production Design',
			'Best Original Score',
			'Best Sound Mixing',
			'Best Sound Editing',
			'Best Visual Effects',
		],
		oscar_winning_list: ['Best Costume Design', 'Best Production Design', 'Best Original Score'],
	},
];
